-- Slice 2: catalog/security and behavior proof for the local atomic RPC.
begin;
create extension if not exists pgtap with schema extensions;
select plan(15);
select has_function('public', 'process_mercadopago_billing_event_v2', array['jsonb'], 'T1: v2 billing RPC exists');
select function_returns('public', 'process_mercadopago_billing_event_v2', array['jsonb'], 'jsonb', 'T2: RPC returns JSON');
select ok(not (select prosecdef from pg_proc where oid = 'public.process_mercadopago_billing_event_v2(jsonb)'::regprocedure), 'T3: SECURITY INVOKER');
select ok((select proconfig @> array['search_path=pg_catalog'] from pg_proc where oid = 'public.process_mercadopago_billing_event_v2(jsonb)'::regprocedure), 'T4: search path pinned');
select ok(not has_function_privilege('public', 'public.process_mercadopago_billing_event_v2(jsonb)', 'EXECUTE'), 'T5: PUBLIC denied');
select ok(not has_function_privilege('anon', 'public.process_mercadopago_billing_event_v2(jsonb)', 'EXECUTE'), 'T6: anon denied');
select ok(not has_function_privilege('authenticated', 'public.process_mercadopago_billing_event_v2(jsonb)', 'EXECUTE'), 'T7: authenticated denied');
select ok(has_function_privilege('service_role', 'public.process_mercadopago_billing_event_v2(jsonb)', 'EXECUTE'), 'T8: service role allowed');
select ok(has_table_privilege('service_role', 'public.billing_webhook_events', 'SELECT,INSERT,UPDATE'), 'T9: event privileges');
select ok(has_table_privilege('service_role', 'public.subscriptions', 'SELECT,UPDATE'), 'T10: subscription privileges');
select ok(has_table_privilege('service_role', 'public.workshop_referrals', 'SELECT') and has_table_privilege('service_role', 'public.referral_codes', 'SELECT') and has_table_privilege('service_role', 'public.referral_commissions', 'SELECT,INSERT'), 'T11: referral privileges');
select ok((select relrowsecurity from pg_class where oid = 'public.billing_webhook_events'::regclass) and (select relrowsecurity from pg_class where oid = 'public.subscriptions'::regclass) and (select relrowsecurity from pg_class where oid = 'public.referral_commissions'::regclass), 'T12: RLS enabled');

create function pg_temp.rpc_behavior() returns void language plpgsql as $$
declare w uuid := gen_random_uuid(); s uuid := gen_random_uuid(); y uuid := gen_random_uuid(); c uuid := gen_random_uuid(); p text := 'pre_' || gen_random_uuid(); pay text := 'pay_' || gen_random_uuid(); event_id text := 'event_' || gen_random_uuid(); legacy_id uuid := gen_random_uuid(); result jsonb; before_subscription jsonb; before_event jsonb; commission jsonb := jsonb_build_object('providerPaymentId', pay, 'paymentAmount', 10, 'currency', 'ARS', 'occurredAt', '2026-07-15T10:00:00Z'); input jsonb;
begin
  insert into public.workshops(id,name) values(w,'rpc-test'); insert into public.youtubers(id,display_name) values(y,'rpc-test'); insert into public.referral_codes(id,youtuber_id,code,discount_pct,commission_pct) values(c,y,'rpc-'||w,0,10); insert into public.workshop_referrals(workshop_id,referral_code_id,youtuber_id) values(w,c,y); insert into public.subscriptions(id,workshop_id,status,provider,provider_preapproval_id) values(s,w,'trialing','mercadopago',p);
  input := jsonb_build_object('contractVersion',2,'provider','mercadopago','providerEventId',event_id,'eventType','authorized_payment.created','resourceKind','authorized_payment','providerResourceId',pay,'providerPreapprovalId',p,'providerStatus','authorized','providerSnapshotAt','2026-07-15T10:00:00Z','providerFetchedAt','2026-07-15T10:01:00Z','normalizedPayload','{}'::jsonb,'commission',commission);
  select public.process_mercadopago_billing_event_v2(input) into result;
  if result->>'outcome' <> 'completed' or (select status from public.subscriptions where id=s) <> 'active' or (select count(*) from public.referral_commissions where provider_payment_id=pay) <> 1 or (select payment_amount=10 and commission_pct=10 and commission_amount=1 and currency='ARS' and occurred_at='2026-07-15T10:00:00Z' from public.referral_commissions where provider_payment_id=pay) is not true then raise exception 'success or commission facts failed'; end if;
  select public.process_mercadopago_billing_event_v2(input) into result;
  if result->>'outcome' <> 'duplicate' or (select attempt_count from public.billing_webhook_events where provider_event_id=event_id) <> 1 or (select count(*) from public.referral_commissions where provider_payment_id=pay) <> 1 then raise exception 'completed duplicate mutated'; end if;
  before_subscription := (select to_jsonb(subscriptions) from public.subscriptions where id=s); select to_jsonb(billing_webhook_events) into before_event from public.billing_webhook_events where provider_event_id=event_id;
  select public.process_mercadopago_billing_event_v2(input || jsonb_build_object('providerEventId','stale_'||gen_random_uuid(),'providerSnapshotAt','2020-01-01T00:00:00Z')) into result;
  if result->>'outcome' <> 'stale' or before_subscription <> (select to_jsonb(subscriptions) from public.subscriptions where id=s) then raise exception 'stale mutated subscription'; end if;
  select public.process_mercadopago_billing_event_v2(input || jsonb_build_object('providerResourceId','other_'||gen_random_uuid())) into result;
  if result->>'outcome' <> 'identity_conflict' or before_event <> (select to_jsonb(billing_webhook_events) from public.billing_webhook_events where provider_event_id=event_id) then raise exception 'identity conflict mutated'; end if;
  insert into public.referral_commissions(workshop_id,youtuber_id,referral_code_id,subscription_id,provider_payment_id,payment_amount,commission_pct,commission_amount,currency,occurred_at) values(w,y,c,s,'conflict_'||pay,99,10,9.9,'ARS','2026-07-15T10:00:00Z');
  select public.process_mercadopago_billing_event_v2(input || jsonb_build_object('providerEventId','retry_'||gen_random_uuid(),'providerResourceId','conflict_'||pay,'providerSnapshotAt','2026-07-15T10:02:00Z','providerFetchedAt','2026-07-15T10:03:00Z','commission',commission || jsonb_build_object('providerPaymentId','conflict_'||pay))) into result;
  if result->>'outcome' <> 'retryable' or (select status from public.subscriptions where id=s) <> 'active' then raise exception 'conflict did not rollback'; end if;
  delete from public.referral_commissions where provider_payment_id='conflict_'||pay;
  insert into public.billing_webhook_events(id,provider,provider_event_id,event_type,provider_resource_id,workshop_id) values(legacy_id,'mercadopago','legacy_'||w,'authorized_payment.created',pay,w); before_event := (select to_jsonb(billing_webhook_events) from public.billing_webhook_events where id=legacy_id);
  select public.process_mercadopago_billing_event_v2(input || jsonb_build_object('providerEventId','legacy_'||w,'reconciliation',jsonb_build_object('originalEventId',legacy_id))) into result;
  if result->>'outcome' <> 'completed' or (select contract_version=2 and provider_preapproval_id=p and provider_resource_kind='authorized_payment' from public.billing_webhook_events where id=legacy_id) is not true then raise exception 'safe v1 enrichment failed'; end if;
  insert into public.billing_webhook_events(provider,provider_event_id,event_type,provider_resource_id,workshop_id) values('mercadopago','legacy_bad_'||w,'authorized_payment.created',pay,w); select to_jsonb(billing_webhook_events) into before_event from public.billing_webhook_events where provider_event_id='legacy_bad_'||w;
  select public.process_mercadopago_billing_event_v2(input || jsonb_build_object('providerEventId','legacy_bad_'||w,'providerResourceId','mismatch_'||pay,'reconciliation',jsonb_build_object('originalEventId',(select id from public.billing_webhook_events where provider_event_id='legacy_bad_'||w)))) into result;
  if result->>'outcome' <> 'legacy_uncertain' or before_event <> (select to_jsonb(billing_webhook_events) from public.billing_webhook_events where provider_event_id='legacy_bad_'||w) then raise exception 'legacy mismatch mutated'; end if;
end $$;
select lives_ok('select pg_temp.rpc_behavior()', 'T13: success, retry rollback/correction, duplicate, stale/identity no-mutation, full commission facts, and safe/unsafe legacy behavior');
create function pg_temp.rpc_additional_behavior() returns void language plpgsql as $$
declare a uuid := gen_random_uuid(); b uuid := gen_random_uuid(); c uuid := gen_random_uuid(); sa uuid := gen_random_uuid(); sb uuid := gen_random_uuid(); sc uuid := gen_random_uuid(); legacy uuid := gen_random_uuid(); cross_legacy uuid := gen_random_uuid(); p_a text := 'pre_' || gen_random_uuid(); p_b text := 'pre_' || gen_random_uuid(); p_c text := 'pre_' || gen_random_uuid(); snapshot jsonb; subscriptions_snapshot jsonb; result jsonb; newer jsonb; older jsonb;
begin
  insert into public.workshops(id,name) values(a,'rpc-a'),(b,'rpc-b'),(c,'rpc-c'); insert into public.subscriptions(id,workshop_id,status,provider,provider_preapproval_id) values(sa,a,'trialing','mercadopago',p_a),(sb,b,'trialing','mercadopago',p_b),(sc,c,'trialing','mercadopago',p_c);
  insert into public.billing_webhook_events(id,provider,provider_event_id,event_type,provider_resource_id,workshop_id) values(legacy,'mercadopago','legacy-null-'||a,'authorized_payment.created',null,a); snapshot := (select to_jsonb(e) from public.billing_webhook_events e where id=legacy); subscriptions_snapshot := (select jsonb_agg(to_jsonb(s) order by s.id) from public.subscriptions s where id in (sa,sb));
  select public.process_mercadopago_billing_event_v2(jsonb_build_object('contractVersion',2,'provider','mercadopago','providerEventId','legacy-null-'||a,'eventType','authorized_payment.created','resourceKind','authorized_payment','providerResourceId','payment-'||a,'providerPreapprovalId',p_a,'providerStatus','authorized','providerSnapshotAt','2026-07-15T10:00:00Z','providerFetchedAt','2026-07-15T10:01:00Z','normalizedPayload','{}'::jsonb,'reconciliation',jsonb_build_object('originalEventId',legacy))) into result;
  if result->>'outcome' <> 'legacy_uncertain' or snapshot <> (select to_jsonb(e) from public.billing_webhook_events e where id=legacy) or subscriptions_snapshot <> (select jsonb_agg(to_jsonb(s) order by s.id) from public.subscriptions s where id in (sa,sb)) then raise exception 'null legacy resource mutated billing state'; end if;
  insert into public.billing_webhook_events(id,provider,provider_event_id,event_type,provider_resource_id,workshop_id) values(cross_legacy,'mercadopago','legacy-cross-'||a,'authorized_payment.created','payment-cross-'||a,a); snapshot := (select to_jsonb(e) from public.billing_webhook_events e where id=cross_legacy); subscriptions_snapshot := (select jsonb_agg(to_jsonb(s) order by s.id) from public.subscriptions s where id in (sa,sb));
  select public.process_mercadopago_billing_event_v2(jsonb_build_object('contractVersion',2,'provider','mercadopago','providerEventId','legacy-cross-'||a,'eventType','authorized_payment.created','resourceKind','authorized_payment','providerResourceId','payment-cross-'||a,'providerPreapprovalId',p_b,'providerStatus','authorized','providerSnapshotAt','2026-07-15T10:00:00Z','providerFetchedAt','2026-07-15T10:01:00Z','normalizedPayload','{}'::jsonb,'reconciliation',jsonb_build_object('originalEventId',cross_legacy))) into result;
  if result->>'outcome' <> 'legacy_uncertain' or snapshot <> (select to_jsonb(e) from public.billing_webhook_events e where id=cross_legacy) or subscriptions_snapshot <> (select jsonb_agg(to_jsonb(s) order by s.id) from public.subscriptions s where id in (sa,sb)) then raise exception 'cross-workshop legacy mutated billing state'; end if;
  newer := jsonb_build_object('contractVersion',2,'provider','mercadopago','providerEventId','newer-'||c,'eventType','subscription_preapproval.updated','resourceKind','preapproval','providerResourceId',p_c,'providerPreapprovalId',p_c,'providerStatus','authorized','providerSnapshotAt','2026-07-15T11:00:00Z','providerFetchedAt','2026-07-15T11:01:00Z','normalizedPayload','{}'::jsonb); select public.process_mercadopago_billing_event_v2(newer) into result; if result->>'outcome' <> 'completed' then raise exception 'newer subscription state did not apply'; end if;
  older := newer || jsonb_build_object('providerEventId','older-'||c,'providerStatus','cancelled','providerSnapshotAt','2026-07-15T10:00:00Z','providerFetchedAt','2026-07-15T11:02:00Z'); select public.process_mercadopago_billing_event_v2(older) into result;
  if result->>'outcome' <> 'stale' or (select status from public.subscriptions where id=sc) <> 'active' or (select provider_snapshot_at from public.subscriptions where id=sc) <> '2026-07-15T11:00:00Z'::timestamptz then raise exception 'same-subscription freshness order regressed'; end if;
end $$;
select lives_ok('select pg_temp.rpc_additional_behavior()', 'T14: null-resource and cross-workshop legacy rows are byte-for-byte unchanged; older same-subscription state is stale');
create function pg_temp.rpc_gap_regressions() returns void language plpgsql as $$
declare w uuid := gen_random_uuid(); s uuid := gen_random_uuid(); y uuid := gen_random_uuid(); c uuid := gen_random_uuid(); p text := 'pre_' || gen_random_uuid(); pay text := 'pay_' || gen_random_uuid(); legacy uuid := gen_random_uuid(); missing_event text := 'missing-' || gen_random_uuid(); result jsonb; event_snapshot jsonb; subscription_snapshot jsonb; payload jsonb;
begin
  insert into public.workshops(id,name) values(w,'rpc-gap'); insert into public.youtubers(id,display_name) values(y,'rpc-gap'); insert into public.referral_codes(id,youtuber_id,code,discount_pct,commission_pct) values(c,y,'rpc-gap-'||w,0,10); insert into public.workshop_referrals(workshop_id,referral_code_id,youtuber_id) values(w,c,y); insert into public.subscriptions(id,workshop_id,status,provider,provider_preapproval_id) values(s,w,'trialing','mercadopago',p);
  payload := jsonb_build_object('contractVersion',2,'provider','mercadopago','providerEventId',missing_event,'eventType','authorized_payment.created','resourceKind','authorized_payment','providerResourceId',pay,'providerPreapprovalId',p,'providerStatus','authorized','providerSnapshotAt',null,'providerFetchedAt','2026-07-15T10:01:00Z','normalizedPayload','{}'::jsonb,'commission',jsonb_build_object('providerPaymentId',pay,'paymentAmount',10,'currency','ARS','occurredAt','2026-07-15T10:00:00Z'));
  subscription_snapshot := (select to_jsonb(x) from public.subscriptions x where id=s); select public.process_mercadopago_billing_event_v2(payload) into result;
  if result->>'outcome' <> 'uncertain' or result->>'reason' <> 'missing_provider_timestamp' or subscription_snapshot <> (select to_jsonb(x) from public.subscriptions x where id=s) or (select outcome='uncertain' and outcome_reason='missing_provider_timestamp' from public.billing_webhook_events where provider_event_id=missing_event) is not true then raise exception 'missing payment timestamp mutated or was not durable uncertain'; end if;
  insert into public.billing_webhook_events(id,provider,provider_event_id,event_type,provider_resource_id,workshop_id) values(legacy,'mercadopago','legacy-retry-'||w,'authorized_payment.created','conflict-'||pay,w); insert into public.referral_commissions(workshop_id,youtuber_id,referral_code_id,subscription_id,provider_payment_id,payment_amount,commission_pct,commission_amount,currency,occurred_at) values(w,y,c,s,'conflict-'||pay,99,10,9.9,'ARS','2026-07-15T10:00:00Z');
  payload := payload || jsonb_build_object('providerEventId','legacy-retry-'||w,'providerSnapshotAt','2026-07-15T10:00:00Z','providerResourceId','conflict-'||pay,'commission',jsonb_build_object('providerPaymentId','conflict-'||pay,'paymentAmount',10,'currency','ARS','occurredAt','2026-07-15T10:00:00Z'),'reconciliation',jsonb_build_object('originalEventId',legacy));
  select public.process_mercadopago_billing_event_v2(payload) into result;
  if result->>'outcome' <> 'retryable' or (select contract_version=2 and outcome='retryable' and provider_preapproval_id=p and provider_resource_kind='authorized_payment' from public.billing_webhook_events where id=legacy) is not true or (select status from public.subscriptions where id=s) <> 'trialing' or (select count(*) from public.referral_commissions where provider_payment_id='conflict-'||pay) <> 1 then raise exception 'v1 failure leaked effects or lost durable v2 retry evidence'; end if;
  delete from public.referral_commissions where provider_payment_id='conflict-'||pay; select public.process_mercadopago_billing_event_v2(payload - 'reconciliation') into result;
  if result->>'outcome' <> 'completed' or (select count(*) from public.referral_commissions where provider_payment_id='conflict-'||pay) <> 1 then raise exception 'strict v2 retry did not complete exactly once'; end if;
  if has_table_privilege('service_role','public.workshops','INSERT,UPDATE,DELETE') or has_table_privilege('service_role','public.profiles','INSERT,UPDATE,DELETE') then raise exception 'service role gained unneeded workshop/profile writes'; end if;
  select public.process_mercadopago_billing_event_v2(payload || jsonb_build_object('providerEventId','equal-snapshot-older-fetch-'||w,'providerStatus','cancelled','providerFetchedAt','2026-07-15T10:00:00Z')) into result;
  if result->>'outcome' <> 'stale' or (select status from public.subscriptions where id=s) <> 'active' then raise exception 'equal snapshot older fetch regressed access'; end if;
  select public.process_mercadopago_billing_event_v2(jsonb_build_object('contractVersion',2,'provider','mercadopago','providerEventId','referred-preapproval-'||w,'eventType','subscription_preapproval.updated','resourceKind','preapproval','providerResourceId',p,'providerPreapprovalId',p,'providerStatus','paused','providerSnapshotAt','2026-07-15T10:02:00Z','providerFetchedAt','2026-07-15T10:03:00Z','normalizedPayload','{}'::jsonb)) into result;
  if result->>'outcome' <> 'completed' or (select status from public.subscriptions where id=s) <> 'past_due' then raise exception 'referred preapproval without commission did not complete'; end if;
end $$;
select lives_ok('select pg_temp.rpc_gap_regressions()', 'T15: missing payment timestamp is durable uncertain; v1 failure persists only v2 retry evidence; strict retry is exactly-once; service role lacks workshop/profile writes');
select * from finish();
rollback;
