import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import path from "path";

export default defineConfig({
	plugins: [
		react(),
		VitePWA({
			registerType: "autoUpdate",
			includeAssets: ["favicon.ico", "icons/*.png"],
			manifest: {
				name: "CarpinteroPro",
				short_name: "CarpinteroPro",
				description: "Gestión integral de taller de carpintería",
				theme_color: "#1e293b",
				background_color: "#ffffff",
				display: "standalone",
				orientation: "portrait",
				start_url: "/dashboard",
				icons: [
					{ src: "icons/icon-192.png", sizes: "192x192", type: "image/png" },
					{ src: "icons/icon-512.png", sizes: "512x512", type: "image/png" },
					{
						src: "icons/icon-512.png",
						sizes: "512x512",
						type: "image/png",
						purpose: "maskable",
					},
				],
			},
			workbox: {
				globPatterns: ["**/*.{js,css,html,ico,png,svg}"],
				skipWaiting: true,
				clientsClaim: true,
			},
		}),
	],
	resolve: {
		alias: { "@": path.resolve(__dirname, "./src") },
		dedupe: ["react", "react-dom"],
	},
	// coverage-regression-gate — baseline measured 2026-06-28
	// Baseline: lines=72.86, branches=64.14, functions=63.79, statements=71.7
	// Conservative floor at 50; ratchet thresholds upward as coverage improves;
	// never lower them without design review.
	test: {
		globals: true,
		environment: "jsdom",
		setupFiles: "./tests/setup.ts",
		exclude: ["tests/e2e/**", "node_modules/**", "dist/**"],
		allowOnly: !process.env.CI,
		coverage: {
			provider: "v8",
			reporter: ["text", "html", "lcov", "json"],
			exclude: [
				// Tests and test infrastructure
				"tests/**",
				"tests/e2e/**",
				"**/*.test.{ts,tsx}",
				// Build output and coverage reports
				"dist/**",
				"coverage/**",
				// TypeScript declaration files (generated by tsc)
				"**/*.d.ts",
				// Shared generated database types (manually maintained, excluded from coverage)
				"src/shared/lib/database.ts",
				// Supabase Edge Functions and migrations (Deno/PostgreSQL, not Vitest)
				"supabase/functions/**",
				"supabase/migrations/**",
				// Vite/configuration files
				"vite.config.ts",
				"vite.config.test.ts",
			],
			// Thresholds set conservatively at or below measured baseline; see design §Thresholds
			thresholds: { lines: 50, branches: 50, functions: 50, statements: 50 },
		},
	},
});
