-- Remote migration history placeholder.
--
-- Version `20260417092836` / `material_dimensions` is already applied in the linked Supabase
-- project history. The executable schema for local development is represented
-- by `0006_material_dimensions.sql` in this repository.
--
-- Keep this file comment-only. It exists so `supabase migration list --linked`
-- can reconcile the remote timestamp ledger without replaying duplicate
-- historical DDL during local resets or future pushes.
