// Auto-generated by: supabase gen types typescript --project-id <id> > src/shared/types/database.ts
// Run after each migration to keep types in sync.
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
